# LeafToLife Inventory API Test Script
# Generated by Morpheus

$BASE_URL = "http://localhost:5001/api"
$TOKEN = ""

# Step 1: Get fresh JWT token
try {
    $authResponse = Invoke-WebRequest -Uri "$BASE_URL/auth/login" -Method POST -Headers @{ "Content-Type"="application/json" } -Body '{"email":"superadmin@leaftolife.com.sg","password":"NewPassword123!"}' -UseBasicParsing
    $TOKEN = ($authResponse.Content | ConvertFrom-Json).accessToken
    Write-Host "AUTH: Token acquired OK" -ForegroundColor Green
} catch {
    Write-Host "AUTH FAILED: $_" -ForegroundColor Red
    exit 1
}

$HEADERS = @{
    "Authorization" = "Bearer $TOKEN"
    "Content-Type"  = "application/json"
}

# Results storage
$results = @()

function Test-Endpoint {
    param(
        [string]$Label,
        [string]$Method,
        [string]$Url,
        [string]$Body = $null
    )
    try {
        if ($Body) {
            $resp = Invoke-WebRequest -Uri $Url -Method $Method -Headers $HEADERS -Body $Body -UseBasicParsing -ErrorAction Stop
        } else {
            $resp = Invoke-WebRequest -Uri $Url -Method $Method -Headers $HEADERS -UseBasicParsing -ErrorAction Stop
        }
        $status = $resp.StatusCode
        $pass = if ($status -ge 200 -and $status -lt 300) { "PASS" } else { "FAIL" }
        $notes = ""
        return [PSCustomObject]@{ Endpoint=$Label; Status=$status; Result=$pass; Notes=$notes; Body=$resp.Content }
    } catch {
        $status = 0
        if ($_.Exception.Response) {
            $status = [int]$_.Exception.Response.StatusCode
        }
        return [PSCustomObject]@{ Endpoint=$Label; Status=$status; Result="FAIL"; Notes=$_.Exception.Message.Split("`n")[0]; Body="" }
    }
}

Write-Host "`n=== UNITS ===" -ForegroundColor Cyan

# GET /inventory/units
$r = Test-Endpoint "GET /inventory/units" "GET" "$BASE_URL/inventory/units"
$results += $r

# GET /inventory/units/:id (known ID)
$r = Test-Endpoint "GET /inventory/units/:id" "GET" "$BASE_URL/inventory/units/68acf68a7ed2e820738bf371"
$results += $r

# POST /inventory/units
$newUnitBody = '{"name":"TestUnit_API","abbreviation":"TU","description":"API test unit"}'
$r = Test-Endpoint "POST /inventory/units" "POST" "$BASE_URL/inventory/units" $newUnitBody
$results += $r
$createdUnitId = $null
if ($r.Result -eq "PASS" -and $r.Body) {
    try { $createdUnitId = ($r.Body | ConvertFrom-Json)._id } catch {}
    if (-not $createdUnitId) {
        try { $createdUnitId = ($r.Body | ConvertFrom-Json).data._id } catch {}
    }
}
Write-Host "  Created unit ID: $createdUnitId"

# PUT /inventory/units/:id
if ($createdUnitId) {
    $updateUnitBody = '{"name":"TestUnit_API_Updated","abbreviation":"TUU","description":"Updated API test unit"}'
    $r = Test-Endpoint "PUT /inventory/units/:id" "PUT" "$BASE_URL/inventory/units/$createdUnitId" $updateUnitBody
} else {
    $r = [PSCustomObject]@{ Endpoint="PUT /inventory/units/:id"; Status=0; Result="SKIP"; Notes="No created unit ID" }
}
$results += $r

# DELETE /inventory/units/:id
if ($createdUnitId) {
    $r = Test-Endpoint "DELETE /inventory/units/:id" "DELETE" "$BASE_URL/inventory/units/$createdUnitId"
} else {
    $r = [PSCustomObject]@{ Endpoint="DELETE /inventory/units/:id"; Status=0; Result="SKIP"; Notes="No created unit ID" }
}
$results += $r

Write-Host "`n=== CATEGORIES ===" -ForegroundColor Cyan

# GET /inventory/categories
$r = Test-Endpoint "GET /inventory/categories" "GET" "$BASE_URL/inventory/categories"
$results += $r
$firstCatId = $null
if ($r.Result -eq "PASS" -and $r.Body) {
    try {
        $cats = $r.Body | ConvertFrom-Json
        if ($cats -is [array] -and $cats.Count -gt 0) { $firstCatId = $cats[0]._id }
        elseif ($cats.data -is [array] -and $cats.data.Count -gt 0) { $firstCatId = $cats.data[0]._id }
    } catch {}
}
Write-Host "  First category ID: $firstCatId"

# GET /inventory/categories/:id
if ($firstCatId) {
    $r = Test-Endpoint "GET /inventory/categories/:id" "GET" "$BASE_URL/inventory/categories/$firstCatId"
} else {
    $r = [PSCustomObject]@{ Endpoint="GET /inventory/categories/:id"; Status=0; Result="SKIP"; Notes="No category ID available" }
}
$results += $r

# POST /inventory/categories
$newCatBody = '{"name":"TestCategory_API","description":"API test category"}'
$r = Test-Endpoint "POST /inventory/categories" "POST" "$BASE_URL/inventory/categories" $newCatBody
$results += $r
$createdCatId = $null
if ($r.Result -eq "PASS" -and $r.Body) {
    try { $createdCatId = ($r.Body | ConvertFrom-Json)._id } catch {}
    if (-not $createdCatId) {
        try { $createdCatId = ($r.Body | ConvertFrom-Json).data._id } catch {}
    }
}
Write-Host "  Created category ID: $createdCatId"

# PUT /inventory/categories/:id
if ($createdCatId) {
    $updateCatBody = '{"name":"TestCategory_API_Updated","description":"Updated API test category"}'
    $r = Test-Endpoint "PUT /inventory/categories/:id" "PUT" "$BASE_URL/inventory/categories/$createdCatId" $updateCatBody
} else {
    $r = [PSCustomObject]@{ Endpoint="PUT /inventory/categories/:id"; Status=0; Result="SKIP"; Notes="No created category ID" }
}
$results += $r

# DELETE /inventory/categories/:id
if ($createdCatId) {
    $r = Test-Endpoint "DELETE /inventory/categories/:id" "DELETE" "$BASE_URL/inventory/categories/$createdCatId"
} else {
    $r = [PSCustomObject]@{ Endpoint="DELETE /inventory/categories/:id"; Status=0; Result="SKIP"; Notes="No created category ID" }
}
$results += $r

Write-Host "`n=== PRODUCTS ===" -ForegroundColor Cyan

# GET /inventory/products/stats
$r = Test-Endpoint "GET /inventory/products/stats" "GET" "$BASE_URL/inventory/products/stats"
$results += $r

# GET /inventory/products
$r = Test-Endpoint "GET /inventory/products" "GET" "$BASE_URL/inventory/products"
$results += $r
$firstProductId = $null
if ($r.Result -eq "PASS" -and $r.Body) {
    try {
        $prods = $r.Body | ConvertFrom-Json
        if ($prods -is [array] -and $prods.Count -gt 0) { $firstProductId = $prods[0]._id }
        elseif ($prods.data -is [array] -and $prods.data.Count -gt 0) { $firstProductId = $prods.data[0]._id }
        elseif ($prods.products -is [array] -and $prods.products.Count -gt 0) { $firstProductId = $prods.products[0]._id }
    } catch {}
}
Write-Host "  First product ID: $firstProductId"

# GET /inventory/products/templates
$r = Test-Endpoint "GET /inventory/products/templates" "GET" "$BASE_URL/inventory/products/templates"
$results += $r

# GET /inventory/products/export
$r = Test-Endpoint "GET /inventory/products/export" "GET" "$BASE_URL/inventory/products/export"
$results += $r

# GET /inventory/products/:id
if ($firstProductId) {
    $r = Test-Endpoint "GET /inventory/products/:id" "GET" "$BASE_URL/inventory/products/$firstProductId"
} else {
    $r = [PSCustomObject]@{ Endpoint="GET /inventory/products/:id"; Status=0; Result="SKIP"; Notes="No product ID available" }
}
$results += $r

# POST /inventory/products
$newProdBody = '{"name":"TestProduct_API","sku":"TESTSKU001","description":"API test product","price":9.99,"stock":100,"lowStockThreshold":10}'
$r = Test-Endpoint "POST /inventory/products" "POST" "$BASE_URL/inventory/products" $newProdBody
$results += $r
$createdProductId = $null
if ($r.Result -eq "PASS" -and $r.Body) {
    try { $createdProductId = ($r.Body | ConvertFrom-Json)._id } catch {}
    if (-not $createdProductId) {
        try { $createdProductId = ($r.Body | ConvertFrom-Json).data._id } catch {}
    }
    if (-not $createdProductId) {
        try { $createdProductId = ($r.Body | ConvertFrom-Json).product._id } catch {}
    }
}
Write-Host "  Created product ID: $createdProductId"

# PUT /inventory/products/:id
if ($createdProductId) {
    $updateProdBody = '{"name":"TestProduct_API_Updated","description":"Updated API test product","price":19.99}'
    $r = Test-Endpoint "PUT /inventory/products/:id" "PUT" "$BASE_URL/inventory/products/$createdProductId" $updateProdBody
} else {
    $r = [PSCustomObject]@{ Endpoint="PUT /inventory/products/:id"; Status=0; Result="SKIP"; Notes="No created product ID" }
}
$results += $r

# POST /inventory/products/:id/pool
if ($createdProductId) {
    $poolBody = '{"quantity":5,"notes":"API test pool addition"}'
    $r = Test-Endpoint "POST /inventory/products/:id/pool" "POST" "$BASE_URL/inventory/products/$createdProductId/pool" $poolBody
} else {
    $r = [PSCustomObject]@{ Endpoint="POST /inventory/products/:id/pool"; Status=0; Result="SKIP"; Notes="No created product ID" }
}
$results += $r

# DELETE /inventory/products/:id
if ($createdProductId) {
    $r = Test-Endpoint "DELETE /inventory/products/:id" "DELETE" "$BASE_URL/inventory/products/$createdProductId"
} else {
    $r = [PSCustomObject]@{ Endpoint="DELETE /inventory/products/:id"; Status=0; Result="SKIP"; Notes="No created product ID" }
}
$results += $r

# POST /inventory/products/bulk-delete
$bulkDeleteBody = '{"ids":[]}'
$r = Test-Endpoint "POST /inventory/products/bulk-delete" "POST" "$BASE_URL/inventory/products/bulk-delete" $bulkDeleteBody
$results += $r

Write-Host "`n=== RESTOCK ===" -ForegroundColor Cyan

# GET /inventory/restock/suggestions
$r = Test-Endpoint "GET /inventory/restock/suggestions" "GET" "$BASE_URL/inventory/restock/suggestions"
$results += $r

# POST /inventory/restock
$newRestockBody = '{"items":[{"productId":"000000000000000000000001","quantity":10,"notes":"API test order"}],"notes":"API test restock order"}'
$r = Test-Endpoint "POST /inventory/restock" "POST" "$BASE_URL/inventory/restock" $newRestockBody
$results += $r

# GET /inventory/restock
$r = Test-Endpoint "GET /inventory/restock" "GET" "$BASE_URL/inventory/restock"
$results += $r

# POST /inventory/restock/bulk
$bulkRestockBody = '{"orders":[]}'
$r = Test-Endpoint "POST /inventory/restock/bulk" "POST" "$BASE_URL/inventory/restock/bulk" $bulkRestockBody
$results += $r

# GET /inventory/restock/batches
$r = Test-Endpoint "GET /inventory/restock/batches" "GET" "$BASE_URL/inventory/restock/batches"
$results += $r

# =============================================
# SUMMARY TABLE
# =============================================
Write-Host "`n"
Write-Host "=================================================================" -ForegroundColor White
Write-Host " LEAFTOLIFE INVENTORY API TEST RESULTS" -ForegroundColor Yellow
Write-Host "=================================================================" -ForegroundColor White
Write-Host ("{0,-42} {1,-6} {2,-6} {3}" -f "ENDPOINT", "STATUS", "RESULT", "NOTES") -ForegroundColor White
Write-Host ("-" * 100) -ForegroundColor Gray

$passCount = 0
$failCount = 0
$skipCount = 0

foreach ($res in $results) {
    $color = switch ($res.Result) {
        "PASS" { "Green" }
        "FAIL" { "Red" }
        "SKIP" { "Yellow" }
        default { "White" }
    }
    $line = "{0,-42} {1,-6} {2,-6} {3}" -f $res.Endpoint, $res.Status, $res.Result, $res.Notes
    Write-Host $line -ForegroundColor $color

    if ($res.Result -eq "PASS") { $passCount++ }
    elseif ($res.Result -eq "FAIL") { $failCount++ }
    else { $skipCount++ }
}

Write-Host ("-" * 100) -ForegroundColor Gray
Write-Host ""
Write-Host "SUMMARY: $passCount PASS | $failCount FAIL | $skipCount SKIP | Total: $($results.Count)" -ForegroundColor White
Write-Host "=================================================================" -ForegroundColor White
